package leoguedex.com.github.HealthCoachWeb.service;

public class FoodOptions {
    public static final String[] INDICATED_BY = {
            "Amigos",
            "Anúncios",
            "Não fui indicado",
            "Pesquisa na Internet",
            "Outros"};

    public static final String[] REASONS = {
            "Previnir doenças",
            "Melhorar composição corporal",
            "Tratar alergias alimentares",
            "Tratar deficiências nutricionais",
            "Controle de açucar no sangue",
            "Reduzir retenção de líquidos",
            "Melhorar o sistema circulatório",
            "Prevenção de doenças cardíacas",
            "Melhorar saúde renal",
            "Condicionamento físico"
    };

    public static final String[] EXPECTED = {
            "Evitar a longo prazo o aparecimento de doenças",
            "Mudar meu corpo em 6 meses",
            "Reduzir meus problemas com amêndoas",
            "No próximo exame de sangue normalizar minhas vitaminas",
            "Reduzir minhas diabetes",
            "No próximos meses gostaria de reduzir o inchaço causado pela retenção",
            "Gostaria de desentupir minhas veias",
            "Gostaria de uma dieta para auxiliar a saída da pedra do meu rim",
            "Sou atleta e gostaria de me manter em alta performance"
    };
    public static final String[] BREAKFAST = {
            "Aveia com frutas frescas e nozes.",
            "Omelete de claras de ovos com espinafre e tomate.",
            "Iogurte grego com mel e morangos.",
            "Smoothie de banana, espinafre, e proteína em pó.",
            "Mingau de quinoa com amêndoas e cranberries.",
            "Pão integral com abacate e ovo pochê.",
            "Panquecas de aveia com mirtilos e iogurte.",
            "Sanduíche de pão integral com abacate e salmão defumado.",
            "Tofu mexido com vegetais.",
            "Batata-doce assada com canela e iogurte.",
            "Mingau de aveia com sementes de chia e frutas.",
            "Smoothie de abacate e manga.",
            "Waffles integrais com morangos e iogurte.",
            "Pão integral com queijo cottage e abacaxi.",
            "Salada de frutas com nozes e sementes de abóbora.",
            "Wrap de ovos com abacate e salsa.",
            "Mingau de arroz integral com passas e canela.",
            "Tostadas de pão integral com abacate e tomate.",
            "Iogurte de coco com granola e frutas vermelhas.",
            "Sanduíche de manteiga de amendoim e banana em pão integral.",
            "Tofu grelhado com espinafre e cogumelos.",
            "Ovos cozidos com aspargos e tostadas integrais.",
            "Mingau de milho com morangos e nozes.",
            "Smoothie de aveia, banana e manteiga de amendoim.",
            "Batido de espinafre, abacate e maçã.",
            "Tostadas de trigo integral com abacate e ovo cozido.",
            "Salada de grãos com legumes e queijo feta.",
            "Wrap de frango grelhado com hummus e vegetais.",
            "Smoothie de framboesa, amêndoas e iogurte.",
            "Bolinhos de aveia com passas e sementes de girassol."
    };
    public static final String[] SNACK_BEFORE_LUNCH = {
            "Frutas frescas, como maçã ou pera.",
            "Iogurte natural com granola e mel.",
            "Hummus com cenouras baby e aipo.",
            "Um punhado de nozes ou amêndoas.",
            "Um smoothie verde com espinafre, abacate e banana.",
            "Fatias de abacate com um pouco de azeite e pimenta.",
            "Um ovo cozido com um pouco de sal e pimenta.",
            "Uma tigela de sopa de legumes caseira.",
            "Uma salada de quinoa com vegetais e abacate.",
            "Um punhado de uvas ou morangos.",
            "Iogurte grego com nozes e uma pitada de canela.",
            "Um wrap de frango grelhado com alface e tomate.",
            "Fatias de pepino com queijo cottage.",
            "Um smoothie de proteína com proteína em pó e frutas.",
            "Um punhado de castanhas de caju.",
            "Salada de atum com feijão e vegetais.",
            "Um pedaço de queijo com damascos secos.",
            "Um pequeno sanduíche de peito de peru com mostarda.",
            "Mingau de aveia com banana e canela.",
            "Iogurte de coco com abacaxi fresco.",
            "Uma tigela de açaí com granola e frutas.",
            "Fatias de pêra com queijo gorgonzola.",
            "Um punhado de morangos com chantilly de coco.",
            "Um pedaço de salmão grelhado com limão.",
            "Um smoothie de abacaxi e manga.",
            "Um ovo mexido com espinafre e cogumelos.",
            "Salada caprese com tomate, mozzarella e manjericão.",
            "Torrada de trigo integral com abacate e ovo pochê.",
            "Sopa de lentilha com legumes e ervas frescas.",
            "Um pequeno punhado de cerejas ou amoras.",
    };
    public static final String[] LUNCH = {
            "Salada de frango grelhado com vegetais frescos.",
            "Salmão assado com quinoa e espargos.",
            "Frango ao curry com arroz integral.",
            "Salada de atum com feijão, milho e abacate.",
            "Tofu stir-fry com legumes e molho de amendoim.",
            "Espaguete de abobrinha com molho de tomate caseiro.",
            "Sopa de lentilha com legumes.",
            "Wrap de vegetais grelhados com hummus.",
            "Omelete de cogumelos com salada verde.",
            "Peito de frango grelhado com batata-doce.",
            "Lentilhas com arroz basmati e legumes.",
            "Salada de quinoa com abacate e coentro.",
            "Salmão com salada de rúcula e morangos.",
            "Tigela de arroz integral com tofu e legumes cozidos no vapor.",
            "Espaguete de grão de bico com molho de tomate.",
            "Peito de peru assado com brócolis e cenouras.",
            "Salada de feijão preto com milho, pimentão e coentro.",
            "Frango ao pesto com macarrão de abobrinha.",
            "Tigela de arroz integral com feijão e abacate.",
            "Sopa de abóbora com gengibre e creme de coco.",
            "Wrap de frango grelhado com alface e tomate.",
            "Salmão grelhado com aspargos e purê de batata-doce.",
            "Tigela de arroz de couve-flor com legumes e amêndoas.",
            "Frango teriyaki com arroz de couve-flor.",
            "Salada de camarão com abacate e coentro.",
            "Tigela de macarrão de trigo integral com legumes e molho de amendoim.",
            "Salada de quinoa com grão de bico e legumes assados.",
            "Tigela de arroz integral com tofu e vegetais grelhados.",
            "Tigela de macarrão de arroz com frango e vegetais stir-fry.",
            "Salada de atum com feijão-branco, tomate e manjericão.",
    };
    public static final String[] AFTERNOON_SNACK = {
            "Um punhado de cenouras baby com hummus.",
            "Um smoothie de banana e espinafre.",
            "Iogurte grego com frutas vermelhas.",
            "Um punhado de amêndoas ou nozes.",
            "Fatias de maçã com manteiga de amendoim.",
            "Torradas integrais com abacate e pimenta.",
            "Uma tigela de sopa de legumes caseira.",
            "Um punhado de uvas ou morangos.",
            "Hummus com aipo e pimentões.",
            "Iogurte de coco com granola e mel.",
            "Tigela de açaí com granola e frutas.",
            "Pedaço de queijo com damascos secos.",
            "Smoothie de proteína com frutas e espinafre.",
            "Torrada integral com abacate e ovo cozido.",
            "Sopa de lentilha com legumes.",
            "Um pequeno punhado de cerejas ou amoras.",
            "Um punhado de castanhas de caju.",
            "Pedaço de queijo com peras fatiadas.",
            "Iogurte grego com mel e nozes.",
            "Smoothie de abacate e manga.",
            "Pão integral com salmão defumado.",
            "Uma tigela de aveia com frutas frescas.",
            "Tofu grelhado com legumes.",
            "Batido de espinafre, abacate e maçã.",
            "Pedaço de queijo cottage com abacaxi.",
            "Um punhado de mirtilos e um iogurte.",
            "Wrap de frango grelhado com alface e tomate.",
            "Salada de frutas com iogurte.",
            "Uma fatia de melancia com limão espremido.",
    };
    public static final String[] DINNER = {
            "Peito de frango grelhado com brócolis e arroz integral.",
            "Salmão assado com aspargos e quinoa.",
            "Espaguete de abobrinha com molho de tomate caseiro.",
            "Tigela de arroz integral com tofu e legumes cozidos no vapor.",
            "Sopa de lentilha com vegetais.",
            "Wrap de vegetais grelhados com hummus.",
            "Frango ao curry com arroz integral.",
            "Salada de atum com feijão, milho e abacate.",
            "Tofu stir-fry com legumes e molho de amendoim.",
            "Mingau de aveia com frutas e nozes.",
            "Salmão com salada de rúcula e morangos.",
            "Salada de quinoa com abacate e coentro.",
            "Tigela de arroz integral com feijão e abacate.",
            "Frango ao pesto com macarrão de abobrinha.",
            "Tigela de arroz de couve-flor com legumes e amêndoas.",
            "Frango teriyaki com arroz de couve-flor.",
            "Sopa de abóbora com gengibre e creme de coco.",
            "Wrap de frango grelhado com alface e tomate.",
            "Salmão grelhado com espargos e purê de batata-doce.",
            "Tigela de macarrão de trigo integral com legumes e molho de amendoim.",
            "Salada de quinoa com grão de bico e legumes assados.",
            "Tigela de arroz integral com tofu e vegetais grelhados.",
            "Tigela de macarrão de arroz com frango e vegetais stir-fry.",
            "Salada de atum com feijão-branco, tomate e manjericão.",
            "Pasta de lentilha vermelha com legumes.",
            "Frango grelhado com salada de pepino e iogurte.",
            "Tigela de arroz integral com salmão grelhado e espinafre.",
            "Abóbora recheada com quinoa, cogumelos e queijo feta.",
            "Salada de camarão com abacate e coentro.",
            "Lasanha de abobrinha com molho de tomate e ricota.",
    };
   public static final String[] BED_TIME_SNACKS = {
            "Um punhado de nozes ou amêndoas.",
            "Iogurte grego com mel e frutas.",
            "Torradas integrais com abacate e uma pitada de sal.",
            "Uma fatia de queijo com uvas ou peras.",
            "Banana com manteiga de amendoim.",
            "Chá de camomila com uma colher de mel.",
            "Tigela de cereais integrais com leite.",
            "Fatias de maçã com canela e um pouco de queijo cottage.",
            "Um smoothie de proteína com frutas e espinafre.",
            "Um punhado de morangos com iogurte grego.",
            "Uma fatia de pão integral com abacate.",
            "Tigela de aveia com uma pitada de canela.",
            "Iogurte de coco com pedaços de coco e nozes.",
            "Um ovo cozido com uma pitada de sal e pimenta.",
            "Tigela de arroz integral com leite de amêndoas e canela.",
            "Fatias de pera com queijo cottage e nozes.",
            "Um smoothie de banana e abacate.",
            "Chia pudding com frutas vermelhas.",
            "Torradas de trigo integral com manteiga de amendoim.",
            "Pedaço de queijo com damascos secos.",
            "Uma tigela de sopa de legumes leve.",
            "Pedaço de salmão grelhado com espargos.",
            "Tigela de iogurte grego com granola e mel.",
            "Pedaço de melancia com limão espremido.",
            "Um punhado de cerejas ou amoras.",
            "Uma fatia de melão com presunto magro.",
            "Batido de abacate e manga com proteína em pó.",
            "Um punhado de mirtilos com um iogurte.",
            "Tigela de aveia com passas e nozes.",
            "Tigela de arroz de couve-flor com cogumelos e queijo parmesão."
    };
}
