package leoguedex.com.github.HealthCoachWeb.service;

public class PhysicalActivityOptions {
    public static final String[] TYPES_EXERCISES = {
            "Caminhada",
            "Corrida",
            "Ciclismo",
            "Natação",
            "Musculação",
            "Yoga",
            "Pilates",
            "Treinamento Funcional",
            "CrossFit",
            "Dança",
            "Aeróbica",
            "Jump",
            "Hidroginástica",
            "Tai Chi",
            "Boxe",
            "Artes Marciais",
            "Escalada",
            "Remo",
            "Pular Corda",
            "Spinning",
            "Treinamento HIIT",
            "Alongamento",
            "Treinamento de Flexibilidade",
            "Treinamento de Equilíbrio",
            "Treinamento de Resistência",
            "Treinamento de Velocidade",
            "Treinamento de Agilidade",
            "Treinamento de Potência",
            "Treinamento de Coordenação",
    };
    public static final String[] FEELINGS_POS_EXERCISE = {
            "Energizado",
            "Revigorado",
            "Fresco",
            "Fortalecido",
            "Renovado",
            "Motivado",
            "Ativo",
            "Animado",
            "Inspirado",
            "Cheio de energia",
            "Feliz",
            "Leve",
            "Satisfeito",
            "Confiante",
            "Realizado",
            "Desperto",
            "Revitalizado",
            "Vigoroso",
            "Radiante",
            "Revitalizado",
            "Elevado",
            "Grato",
            "Tranquilo",
            "Aliviado",
            "Sociável",
            "Alegre",
            "Focado",
            "Relaxado",
            "Motivado",
            "Eufórico"
    };
    public static final String[] FREE_TIME_ACTIVITIES = {
            "Hiking",
            "Swimming",
            "Cycling",
            "Running",
            "Yoga",
            "Reading",
            "Painting",
            "Cooking",
            "Gardening",
            "Photography",
            "Playing a musical instrument",
            "Dancing",
            "Meditation",
            "Watching movies",
            "Traveling",
            "Playing sports",
            "Writing",
            "Birdwatching",
            "Fishing",
            "Volunteering",
            "Gaming",
            "Horseback riding",
            "Camping",
            "Collecting",
            "Stargazing",
            "Crafting",
            "Singing",
            "Skiing",
            "Sailing",
            "Scuba diving"
    };
    public static final String[] EXERCISE_LIMITATIONS = {
            "Knee injury",
            "Back pain",
            "Shoulder injury",
            "Arthritis",
            "Hip injury",
            "Asthma",
            "Heart condition",
            "Pregnancy",
            "Diabetes",
            "High blood pressure",
            "Osteoporosis",
            "COPD (Chronic obstructive pulmonary disease)",
            "Obesity",
            "Fibromyalgia",
            "Anxiety",
            "Depression",
            "Multiple sclerosis",
            "Parkinson's disease",
            "Cerebral palsy",
            "Muscular dystrophy",
            "Cancer",
            "Eating disorder",
            "Herniated disc",
            "Rheumatoid arthritis",
            "Epilepsy",
            "Hemophilia",
            "Osteoarthritis",
            "Stroke",
            "Thyroid disorder"
    };
    public static final String[] SUPPLEMENTS = {
            "Protein powder",
            "Creatine",
            "Multivitamin",
            "Fish oil",
            "Vitamin D",
            "BCAA (Branched-Chain Amino Acids)",
            "Glutamine",
            "Pre-workout supplement",
            "Whey protein",
            "Casein protein",
            "BCAA",
            "Beta-Alanine",
            "L-Carnitine",
            "L-Glutamine",
            "Vitamin C",
            "ZMA (Zinc, Magnesium, Vitamin B6)",
            "Vitamin B12",
            "Iron supplement",
            "Calcium supplement",
            "Vitamin E",
            "Fiber supplement",
            "Collagen",
            "Probiotics",
            "Joint support supplement",
            "Melatonin (for sleep)",
            "Electrolyte supplement",
            "Green tea extract",
            "Spirulina",
            "Ginseng",
            "Ashwagandha",
            "Turmeric (Curcumin)",
    };
    public static final String[] DESIRED_FREE_TIME_ACTIVITIES = {
            "Traveling",
            "Hiking",
            "Swimming",
            "Reading",
            "Cooking",
            "Photography",
            "Playing a musical instrument",
            "Dancing",
            "Meditation",
            "Watching movies",
            "Playing sports",
            "Traveling abroad",
            "Skiing",
            "Exploring new places",
            "Volunteering",
            "Gaming",
            "Camping",
            "Birdwatching",
            "Fishing",
            "Trying new restaurants",
            "Horseback riding",
            "Cycling",
            "Relaxing at the beach",
            "Collecting",
            "Stargazing",
            "Crafting",
            "Singing",
            "Sailing",
            "Scuba diving",
            "Visiting art galleries",
    };
    public static final String[] LIFE_SITUATIONS_TO_CHANGE = {
            "Stressful job",
            "Unhealthy lifestyle",
            "Lack of work-life balance",
            "Financial stress",
            "Relationship issues",
            "Health concerns",
            "Procrastination",
            "Negative mindset",
            "Loneliness",
            "Time management",
            "Low self-esteem",
            "Family conflicts",
            "Unfulfilled dreams",
            "Weight management",
            "Career change",
            "Overcoming fears",
            "Personal growth",
            "Addiction recovery",
            "Time for self-care",
            "Mental health",
            "Fitness journey",
            "Learning new skills",
            "Finding passion",
            "Building relationships",
            "Workplace challenges",
            "Managing stress",
            "Dealing with anxiety",
            "Handling emotions",
            "Finding purpose",
            "Financial stability"
    };
}
